### PR TITLE
Patch for kenels >= 5.0

### PR DESCRIPTION
**Pull request by CPT-GrayWolf**
Okay. For real this time.
After accidentally deleting a comment bracket, breaking backwards compatibility, and some fiddling around, I have solved the problem for real.

### CODE REVIEW

**Comment by lanconnected** [comment]
Thanks for the patch, i'll merge it if it doesn't break backwards compatibility. I'll test it probably at monday.

**Comment by CPT-GrayWolf** [comment]
Well, I used your compatibility definitions this time, like not an idiot who isn't paying attention. So the code should essentially remain unchanged for older kernels.

I'll probably stick around from now on and help where I can. I'm not much of a kernel driver developer, so a lot of the code is lost on me, but I should at least be able to help keep it running. Maybe I'll help update the documentation.

I have a plan to make packages available. That way people who are afraid of git and make will be able to use this project.

**Comment by lanconnected** [comment]
Thanks a lot! I'm planning a bit bigger update to a code, which changes configuration approach as well. Testing and help with the documentation are very welcome!

**Comment by CPT-GrayWolf** [comment]
I've added a script to make installation less of a headache, as well as updated Install.txt. 

Manually preforming all the steps for each new kernel and each new system was driving me insane.

**Comment by lanconnected** [comment]
Merged. Thanks.

**Pull request merged**
